### ISSUE TITLE
Direct Import Option

### ISSUE THREAD

**Issue by voidstate** [randolphw/han-shopped-first#2]
Hello

I'm the developer of the Unofficial Squadron Builder. Currently, on my XWS page , you can export directly to Fab's and Geordan's builders. Well, I think Han Shopped First is brilliant and would like to export directly to it. 

Any chance you could make that an option? I could POST the XWS data or use a web service... whatever is best for you.

You can see an example of a direct export here: http://xwing-builder.co.uk/xws/404935 (click the "Export to..." button).

Let me know if you're interested and we can get it working. :)

**Comment by randolphw** [comment]
It's live, woo!
